# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "14f2c5b416cc97de1f341a5454b9c0bb"
name = "CompareFlow"
application_url = "https://compareflow.salesvision.shop"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app_subscriptions/update"
  topics = [ "app_subscriptions/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/delete"
  topics = [ "products/delete" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/update"
  topics = [ "products/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/update"
  topics = [ "shop/update" ]

[access_scopes]
scopes = "read_products,write_products,read_themes,write_script_tags"

[webhooks.privacy_compliance]
customer_deletion_url = "https://compareflow.salesvision.shop/webhooks/customers/redact"
customer_data_request_url = "https://compareflow.salesvision.shop/webhooks/customers/data_request"
shop_deletion_url = "https://compareflow.salesvision.shop/webhooks/shop/redact"

[app_proxy]
url = "https://compareflow.salesvision.shop/api"
subpath = "compareflow"
prefix = "apps"

[auth]
redirect_urls = [ 
  "https://compareflow.salesvision.shop/auth/callback",
  "https://compareflow.salesvision.shop/auth/shopify/callback"
]
